### PR TITLE
give tshirt uwu

### PR DESCRIPTION
**Pull request by lukasnacht**
be careful what you wish for

### CODE REVIEW

**Comment by wtfismyip** [comment]
That's the fucking spirit!

**Comment by ruoho-sfdc** [comment]
Maybe it should be "awesome fucking endpoints". I really want you to get a fucking tshirt.

**Comment by wtfismyip** [comment]
Maybe it should be "awesome fucking endpoints". I really want you to get a fucking tshirt.

**Comment by wtfismyip** [comment]
Closed. No t-shirt for you.

**Pull request closed without merging**
